### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by UAWDHiuhawidubhaq2312ouadsh** [h0nde/roblox-claimable-group-finder#35]
Traceback (most recent call last):
  File "finder.py", line 1, in <module>
    from lib.controllers import Controller
  File "C:\Users\drevo\OneDrive\Desktop\roblox-claimable-group-finder-main\lib\controllers.py", line 26
    while (line := fp.readline()):
                ^
SyntaxError: invalid syntax

**Comment by h0nde** [comment]
Install Python 3.8 or [later](https://www.python.org/downloads/).
