### ISSUE TITLE
frozen importlib._bootstrap?

### ISSUE THREAD

**Issue by MoeenTheSkid** [h0nde/roblox-claimable-group-finder#53]
what do i do lol i have this really long error?

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process Worker-13:
Process Worker-14:
Process Worker-6:
Process Worker-2:
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
    self.run()
    self.run()
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self.run()
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    self.run()
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    self.run()
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._cond = Condition(Lock())
RuntimeError: can't allocate lock
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    thread = Thread(
    thread = Thread(
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._started = Event()
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._cond = Condition(Lock())
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._cond = Condition(Lock())
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._started = Event()
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._started = Event()
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._cond = Condition(Lock())
RuntimeError: can't allocate lock
    self._cond = Condition(Lock())
    self._started = Event()
    self._started = Event()
    self._started = Event()
    thread = Thread(
RuntimeError: can't allocate lock
    self._cond = Condition(Lock())
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._started = Event()
    self._cond = Condition(Lock())
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
RuntimeError: can't allocate lock
    self._started = Event()
RuntimeError: can't allocate lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__

During handling of the above exception, another exception occurred:

RuntimeError: can't allocate lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._cond = Condition(Lock())
RuntimeError: can't allocate lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__

During handling of the above exception, another exception occurred:

    self._cond = Condition(Lock())
    self._cond = Condition(Lock())
    self._cond = Condition(Lock())
Traceback (most recent call last):
    self._started = Event()

During handling of the above exception, another exception occurred:

    self._cond = Condition(Lock())
RuntimeError: can't allocate lock

During handling of the above exception, another exception occurred:

  File "D:\Disk\Downloads\roblox-claimable-group-finder-main\roblox-claimable-group-finder-main\lib\workers.py", line 15, in worker_func
    thread = Thread(
    thread = Thread(
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
Traceback (most recent call last):
RuntimeError: can't allocate lock
RuntimeError: can't allocate lock
RuntimeError: can't allocate lock
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
Traceback (most recent call last):
RuntimeError: can't allocate lock
    self._cond = Condition(Lock())
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 869, in __init__
    self._started = Event()
    self._cond = Condition(Lock())
  File "<string>", line 1, in <module>
    self._started = Event()

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "<string>", line 1, in <module>

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
RuntimeError: can't allocate lock
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
    self._cond = Condition(Lock())
RuntimeError: can't allocate lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\threading.py", line 539, in __init__
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>

During handling of the above exception, another exception occurred:

    exitcode = _main(fd, parent_sentinel)
RuntimeError: can't allocate lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main

During handling of the above exception, another exception occurred:

    self._cond = Condition(Lock())
  File "<string>", line 1, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
Traceback (most recent call last):
RuntimeError: can't allocate lock
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    exitcode = _main(fd, parent_sentinel)
  File "<string>", line 1, in <module>

During handling of the above exception, another exception occurred:

  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    exitcode = _main(fd, parent_sentinel)
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
Traceback (most recent call last):
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    import traceback
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
    import traceback
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
    exitcode = _main(fd, parent_sentinel)
  File "<string>", line 1, in <module>
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 170, in __enter__
    import traceback
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 170, in __enter__
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
    import traceback
    import traceback
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    import traceback
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
    import traceback
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
    import traceback
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 72, in __init__
    return self._bootstrap(parent_sentinel)
RuntimeError: can't allocate lock
    import traceback
  File "<frozen importlib._bootstrap>", line 72, in __init__
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap>", line 170, in __enter__
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 170, in __enter__
    import traceback
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap>", line 170, in __enter__
    import traceback
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "C:\Users\lmali\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 329, in _bootstrap
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 72, in __init__
  File "<frozen importlib._bootstrap>", line 72, in __init__
    import traceback
  File "<frozen importlib._bootstrap>", line 72, in __init__
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 72, in __init__
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 170, in __enter__
RuntimeError: can't allocate lock
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
RuntimeError: can't allocate lock
RuntimeError: can't allocate read lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
RuntimeError: can't allocate read lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
RuntimeError: can't allocate lock
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
RuntimeError: can't allocate lock

**Comment by zaxhodV2** [comment]
you just posted a nuclear bomb bruh

**Comment by MoeenTheSkid** [comment]
lol yeah but seriously how do I fix this xd

**Comment by zaxhodV2** [comment]
So basically you either is trying to host on a non supportive thread vps or you tried editing the source code and you messed up or it has to do with your threads you put.

**Comment by zaxhodV2** [comment]
one of these basically

**Comment by MoeenTheSkid** [comment]
Im doing it on my pc, I downloaded it after without touching the source code and I have 500k threads

**Comment by zaxhodV2** [comment]
wtf why 500k threads? smh you needa put 1-150 if you are using 16 workers

**Comment by MoeenTheSkid** [comment]
o h

**Comment by zaxhodV2** [comment]
lmao that will make ur cpu go explode

**Comment by zaxhodV2** [comment]
your pc can't handle that

**Comment by MoeenTheSkid** [comment]
Ig since even 20k crashed my pc

**Comment by zaxhodV2** [comment]
yep. Don't use over 150 threads it will really crash your pc

**Comment by zaxhodV2** [comment]
or make it slow

**Comment by MoeenTheSkid** [comment]
i7, 16 gb ram, the perfect amount for me is 1k threads how much workers should I use?

**Comment by zaxhodV2** [comment]
use 4

**Comment by zaxhodV2** [comment]
if u want it to be less laggy

**Comment by zaxhodV2** [comment]
i don't really think it would be good for 1k threads

**Comment by zaxhodV2** [comment]
its your choice
